# Generated by Django 3.1.4 on 2020-12-21 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('car_Name', models.TextField(max_length=50)),
                ('car_Model', models.TextField(max_length=50)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Unavailable')], default=1)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
