# Generated by Django 3.1.4 on 2020-12-21 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_Name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
