# Generated by Django 3.1.4 on 2020-12-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_auto_20201221_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_licence_Plate',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
