# Generated by Django 3.1.4 on 2020-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_car_car_licence_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cam_url',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
