# Generated by Django 3.1.4 on 2020-12-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Car', '0002_auto_20201221_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('Parking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Parking_Name', models.TextField(max_length=50, unique=True)),
                ('Parking_Address', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_Slot',
            fields=[
                ('Slot_ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Taken'), (2, 'Private')], default=1)),
                ('Parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parking.parking')),
                ('Taken_By', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Car.car')),
            ],
        ),
    ]
