# Generated by Django 3.1.4 on 2020-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parking', '0002_enforcer'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_slot',
            name='Slot_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
