# Generated by Django 3.1.4 on 2020-12-22 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Parking', '0003_parking_slot_slot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_slot',
            name='Rented_By',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
